# Generated by Django 3.2 on 2021-05-03 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_remove_profiles_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profiles',
            old_name='User',
            new_name='user',
        ),
    ]
