# Generated by Django 3.2 on 2021-05-03 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_rename_user_profiles_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='interest',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='phone_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/photos'),
        ),
    ]
