# Generated by Django 3.2 on 2021-05-14 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_rename_profiles_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='sales_or_changes',
            field=models.BigIntegerField(default=0, null=True),
        ),
    ]
