# Generated by Django 3.2 on 2021-05-07 18:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0005_rename_profiles_profile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publication_date', models.DateField(auto_created=True)),
                ('image_front', models.ImageField(upload_to='publications/images/front')),
                ('image_back', models.ImageField(upload_to='publications/images/back')),
                ('description', models.TextField()),
                ('tag_musical_genre', models.CharField(max_length=20)),
                ('price', models.CharField(max_length=20)),
                ('exchange', models.BooleanField(default=False)),
                ('content', models.TextField(default='Contenido no especificado')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
