# Generated by Django 3.2 on 2021-05-07 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='publication_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
