# Generated by Django 3.2 on 2021-05-12 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0002_alter_publication_publication_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='content',
            field=models.CharField(default='Contenido no especificado', max_length=50),
        ),
        migrations.AlterField(
            model_name='publication',
            name='description',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='publication',
            name='price',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='publication',
            name='tag_musical_genre',
            field=models.CharField(max_length=15),
        ),
    ]
