# Generated by Django 3.2 on 2021-05-12 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0004_alter_publication_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='content',
            field=models.CharField(default='Contenido no especificado', max_length=50, null=True),
        ),
    ]
