# Generated by Django 3.2 on 2021-05-12 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0005_alter_publication_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='content',
            field=models.CharField(blank=True, default='Contenido no especificado', max_length=50),
        ),
    ]
