# Generated by Django 3.2 on 2021-05-14 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0006_alter_publication_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='content',
            field=models.CharField(default='Contenido no especificado', max_length=100),
        ),
        migrations.AlterField(
            model_name='publication',
            name='description',
            field=models.CharField(max_length=100),
        ),
    ]
