# Generated by Django 3.2 on 2021-06-08 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0008_publication_availability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='exchange',
            field=models.BooleanField(default=True),
        ),
    ]
