# Generated by Django 3.2 on 2021-06-08 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0009_alter_publication_exchange'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='exchange',
            field=models.BooleanField(default=False),
        ),
    ]
