# Generated by Django 3.2 on 2021-06-15 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0010_alter_publication_exchange'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='content',
            field=models.CharField(blank=True, default='Contenido no especificado', max_length=100),
        ),
    ]
